// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '4004a9fd-d58e-48dc-aeb2-4a4aec58606f',
    name: 'Free Trial',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '1273adef-00a3-4086-a51a-dbcce1857d36',
    registeredProviders: [],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_AD_TEST_USER_PRINCIPAL_NAME'] = 'testUserAuto@rbacCliTest.onmicrosoft.com';
  process.env['AZURE_AD_TEST_PASSWORD'] = 'Pa$$w0rd';
  process.env['AZURE_AD_TEST_GROUP_NAME'] = 'testgroupauto';
  process.env['AZURE_ARM_TEST_LOCATION'] = 'West US';
  process.env['AZURE_AD_TEST_SP_DISPLAY_NAME'] = 'mytestapprandomauto';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2?api-version=2015-05-01-preview', '*')
  .reply(201, "{\"properties\":{\"roleName\":\"TestRole_bff54cc4-1b6b-4586-b3a8-3088d61db60f\",\"type\":\"CustomRole\",\"description\":\"Custom Role Test Desc\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-09-14T17:24:11.4583881Z\",\"updatedOn\":\"2015-09-14T17:24:11.4583881Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"f0fbef93-4466-405a-82c0-2f2e821a2aa2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '751',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '05920cfc-7f8e-4a22-b8c6-eb2ee9c85bd0',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_3',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1192',
  'x-ms-correlation-request-id': '7e59ca02-1bd4-4e3b-85cb-0790dfa85d97',
  'x-ms-routing-request-id': 'WESTUS:20150914T172412Z:7e59ca02-1bd4-4e3b-85cb-0790dfa85d97',
  date: 'Mon, 14 Sep 2015 17:24:12 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2?api-version=2015-05-01-preview', '*')
  .reply(201, "{\"properties\":{\"roleName\":\"TestRole_bff54cc4-1b6b-4586-b3a8-3088d61db60f\",\"type\":\"CustomRole\",\"description\":\"Custom Role Test Desc\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-09-14T17:24:11.4583881Z\",\"updatedOn\":\"2015-09-14T17:24:11.4583881Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"f0fbef93-4466-405a-82c0-2f2e821a2aa2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '751',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '05920cfc-7f8e-4a22-b8c6-eb2ee9c85bd0',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_3',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1192',
  'x-ms-correlation-request-id': '7e59ca02-1bd4-4e3b-85cb-0790dfa85d97',
  'x-ms-routing-request-id': 'WESTUS:20150914T172412Z:7e59ca02-1bd4-4e3b-85cb-0790dfa85d97',
  date: 'Mon, 14 Sep 2015 17:24:12 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('//subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2?api-version=2015-05-01-preview')
  .reply(200, "{\"properties\":{\"roleName\":\"TestRole_bff54cc4-1b6b-4586-b3a8-3088d61db60f\",\"type\":\"CustomRole\",\"description\":\"Custom Role Test Desc\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-09-14T17:24:11.4583881Z\",\"updatedOn\":\"2015-09-14T17:24:11.4583881Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"f0fbef93-4466-405a-82c0-2f2e821a2aa2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '751',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'efb6628c-3d94-4acc-b02d-a696743d73c6',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_3',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-reads': '14985',
  'x-ms-correlation-request-id': '1082deee-4de3-4cf9-bf3a-10543c7bb73f',
  'x-ms-routing-request-id': 'WESTUS:20150914T172414Z:1082deee-4de3-4cf9-bf3a-10543c7bb73f',
  date: 'Mon, 14 Sep 2015 17:24:14 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('//subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2?api-version=2015-05-01-preview')
  .reply(200, "{\"properties\":{\"roleName\":\"TestRole_bff54cc4-1b6b-4586-b3a8-3088d61db60f\",\"type\":\"CustomRole\",\"description\":\"Custom Role Test Desc\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-09-14T17:24:11.4583881Z\",\"updatedOn\":\"2015-09-14T17:24:11.4583881Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"f0fbef93-4466-405a-82c0-2f2e821a2aa2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '751',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'efb6628c-3d94-4acc-b02d-a696743d73c6',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_3',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-reads': '14985',
  'x-ms-correlation-request-id': '1082deee-4de3-4cf9-bf3a-10543c7bb73f',
  'x-ms-routing-request-id': 'WESTUS:20150914T172414Z:1082deee-4de3-4cf9-bf3a-10543c7bb73f',
  date: 'Mon, 14 Sep 2015 17:24:14 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2?api-version=2015-05-01-preview', '*')
  .reply(201, "{\"properties\":{\"roleName\":\"UpdatedRole_a26bca24-6654-4123-8d3a-631d71837ba1\",\"type\":\"CustomRole\",\"description\":\"Updated Role Description\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-09-14T17:24:15.2611904Z\",\"updatedOn\":\"2015-09-14T17:24:15.2611904Z\",\"createdBy\":null,\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"f0fbef93-4466-405a-82c0-2f2e821a2aa2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '723',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '225f297f-310d-4883-8e1c-e889c83c4fbd',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_3',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1194',
  'x-ms-correlation-request-id': '1b5c1219-904f-46d0-b73d-7ca15568ce53',
  'x-ms-routing-request-id': 'WESTUS:20150914T172416Z:1b5c1219-904f-46d0-b73d-7ca15568ce53',
  date: 'Mon, 14 Sep 2015 17:24:15 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2?api-version=2015-05-01-preview', '*')
  .reply(201, "{\"properties\":{\"roleName\":\"UpdatedRole_a26bca24-6654-4123-8d3a-631d71837ba1\",\"type\":\"CustomRole\",\"description\":\"Updated Role Description\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-09-14T17:24:15.2611904Z\",\"updatedOn\":\"2015-09-14T17:24:15.2611904Z\",\"createdBy\":null,\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"f0fbef93-4466-405a-82c0-2f2e821a2aa2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '723',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '225f297f-310d-4883-8e1c-e889c83c4fbd',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_3',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1194',
  'x-ms-correlation-request-id': '1b5c1219-904f-46d0-b73d-7ca15568ce53',
  'x-ms-routing-request-id': 'WESTUS:20150914T172416Z:1b5c1219-904f-46d0-b73d-7ca15568ce53',
  date: 'Mon, 14 Sep 2015 17:24:15 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('//subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2?api-version=2015-05-01-preview')
  .reply(200, "{\"properties\":{\"roleName\":\"UpdatedRole_a26bca24-6654-4123-8d3a-631d71837ba1\",\"type\":\"CustomRole\",\"description\":\"Updated Role Description\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-09-14T17:24:11.4583881Z\",\"updatedOn\":\"2015-09-14T17:24:15.2611904Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"f0fbef93-4466-405a-82c0-2f2e821a2aa2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '757',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'b92dae23-1825-4a80-b7d9-a98232f3042e',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_0',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-reads': '14993',
  'x-ms-correlation-request-id': '1139f3f2-24bf-408c-babc-28b1b244ebdc',
  'x-ms-routing-request-id': 'WESTUS:20150914T172417Z:1139f3f2-24bf-408c-babc-28b1b244ebdc',
  date: 'Mon, 14 Sep 2015 17:24:16 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('//subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2?api-version=2015-05-01-preview')
  .reply(200, "{\"properties\":{\"roleName\":\"UpdatedRole_a26bca24-6654-4123-8d3a-631d71837ba1\",\"type\":\"CustomRole\",\"description\":\"Updated Role Description\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-09-14T17:24:11.4583881Z\",\"updatedOn\":\"2015-09-14T17:24:15.2611904Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"f0fbef93-4466-405a-82c0-2f2e821a2aa2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '757',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'b92dae23-1825-4a80-b7d9-a98232f3042e',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_0',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-reads': '14993',
  'x-ms-correlation-request-id': '1139f3f2-24bf-408c-babc-28b1b244ebdc',
  'x-ms-routing-request-id': 'WESTUS:20150914T172417Z:1139f3f2-24bf-408c-babc-28b1b244ebdc',
  date: 'Mon, 14 Sep 2015 17:24:16 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .delete('//subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2?api-version=2015-05-01-preview')
  .reply(200, "{\"properties\":{\"roleName\":\"UpdatedRole_a26bca24-6654-4123-8d3a-631d71837ba1\",\"type\":\"CustomRole\",\"description\":\"Updated Role Description\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-09-14T17:24:11.4583881Z\",\"updatedOn\":\"2015-09-14T17:24:15.2611904Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"f0fbef93-4466-405a-82c0-2f2e821a2aa2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '757',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'f3983fd5-ddaf-41fd-87b0-6af22ac1aa03',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_3',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1194',
  'x-ms-correlation-request-id': 'e05881a7-80fa-41d8-a2ce-7176b070e56c',
  'x-ms-routing-request-id': 'WESTUS:20150914T172418Z:e05881a7-80fa-41d8-a2ce-7176b070e56c',
  date: 'Mon, 14 Sep 2015 17:24:18 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .delete('//subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2?api-version=2015-05-01-preview')
  .reply(200, "{\"properties\":{\"roleName\":\"UpdatedRole_a26bca24-6654-4123-8d3a-631d71837ba1\",\"type\":\"CustomRole\",\"description\":\"Updated Role Description\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-09-14T17:24:11.4583881Z\",\"updatedOn\":\"2015-09-14T17:24:15.2611904Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/f0fbef93-4466-405a-82c0-2f2e821a2aa2\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"f0fbef93-4466-405a-82c0-2f2e821a2aa2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '757',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'f3983fd5-ddaf-41fd-87b0-6af22ac1aa03',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_3',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1194',
  'x-ms-correlation-request-id': 'e05881a7-80fa-41d8-a2ce-7176b070e56c',
  'x-ms-routing-request-id': 'WESTUS:20150914T172418Z:e05881a7-80fa-41d8-a2ce-7176b070e56c',
  date: 'Mon, 14 Sep 2015 17:24:18 GMT',
  connection: 'close' });
 return result; }]];
 exports.uuidsGenerated = function() { return ['bff54cc4-1b6b-4586-b3a8-3088d61db60f','f0fbef93-4466-405a-82c0-2f2e821a2aa2','a26bca24-6654-4123-8d3a-631d71837ba1'];};